TntRun:
  required-players: 2
  lobby:
    world: 'world'
    x: 0
    y: 0
    z: 0
    pitch: 0
    yaw: 0
  arenas:
    0:
      world: 'world'
      x: 0
      y: 0
      z: 0
      pitch: 0
      yaw: 0
TntTag:
  required-players: 2
  lobby:
    world: 'world'
    x: 0
    y: 0
    z: 0
    pitch: 0
    yaw: 0
  arenas:
    0:
      world: 'world'
      x: 0
      y: 0
      z: 0
      pitch: 0
      yaw: 0
    1:
      world: 'world'
      x: 0
      y: 0
      z: 0
      pitch: 0
      yaw: 0