TntRun:
  lobby:
    x: 0
    y: 0
    z: 0
    pitch: 0
    yaw: 0
  arenas:
    0:
      x: 0
      y: 0
      z: 0
      pitch: 0
      yaw: 0
TntTag:
  lobby:
    x: 0
    y: 0
    z: 0
    pitch: 0
    yaw: 0
  arenas:
    0:
      x: 0
      y: 0
      z: 0
      pitch: 0
      yaw: 0
    1:
      x: 0
      y: 0
      z: 0
      pitch: 0
      yaw: 0